version: "2.3"
services:
  ipsec:
    restart: always
    image: "luscis/openlan:latest.amd64.deb"
    privileged: true
    network_mode: host
    entrypoint: ["/var/openlan/script/ipsec.sh"]
    volumes:
      - /opt/openlan/etc/ipsec.d:/etc/ipsec.d
      - /opt/openlan/run/pluto:/run/pluto
  frr:
    restart: always
    image: "luscis/openlan:latest.amd64.deb"
    network_mode: host
    privileged: true
    entrypoint: ["/var/openlan/script/frr.sh"]
    volumes:
      - /opt/openlan/etc/frr:/etc/frr
      - /opt/openlan/var/openlan/frr:/var/openlan/frr
  switch:
    restart: always
    image: "luscis/openlan:latest.amd64.deb"
    privileged: true
    network_mode: host
    entrypoint: ["/var/openlan/script/switch.sh", "start"]
    volumes:
      - /opt/openlan/etc/openlan:/etc/openlan
      - /opt/openlan/etc/ipsec.d:/etc/ipsec.d
      - /opt/openlan/run/pluto:/run/pluto
      - /opt/openlan/etc/frr:/etc/frr
      - /opt/openlan/var/openlan/frr:/var/openlan/frr
    depends_on:
      - ipsec
      - frr
  proxy:
    restart: always
    image: "luscis/openlan:latest.amd64.deb"
    network_mode: host
    entrypoint: ["/usr/bin/openlan-proxy", "-conf", "/etc/openlan/proxy.json", "-log:file", "/dev/null"]
    volumes:
      - /opt/openlan/etc/openlan:/etc/openlan
    depends_on:
      - switch
#  exporter:
#    restart: always
#    image: "prom/node-exporter:v1.7.0"
#    network_mode: host