version: "2.3"
services:
  ipsec:
    restart: always
    image: "luscis/openlan:latest.x86_64"
    privileged: true
    network_mode: host
    entrypoint: ["/var/openlan/script/ipsec.sh"]
    volumes:
      - /opt/openlan/etc/ipsec.d:/etc/ipsec.d
      - /opt/openlan/run/pluto:/run/pluto
  switch:
    restart: always
    image: "luscis/openlan:latest.x86_64"
    privileged: true
    network_mode: host
    entrypoint: ["/var/openlan/script/switch.sh", "start"]
    volumes:
      - /opt/openlan/etc/openlan:/etc/openlan
      - /opt/openlan/etc/ipsec.d:/etc/ipsec.d
      - /opt/openlan/run/pluto:/run/pluto
    depends_on:
      - ipsec
  proxy:
    restart: always
    image: "luscis/openlan:latest.x86_64"
    network_mode: host
    entrypoint: ["/usr/bin/openlan-proxy", "-conf", "/etc/openlan/proxy.json", "-log:file", "/dev/null"]
    volumes:
      - /opt/openlan/etc/openlan:/etc/openlan
    depends_on:
      - switch
#  exporter:
#    restart: always
#    image: "prom/node-exporter:v1.7.0"
#    network_mode: host